version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp:/var/www/html
       - ./theme:/var/www/html/wp-content/themes/meanpug-challenge-1
       - ./plugins:/var/www/html/wp-content/plugins
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       DEBUG: 1

   static:
     image: dev/meanpug-challenge-1-static
     build:
       context: .
       dockerfile: docker/Dockerfile-static
     volumes:
       - ./gulpfile.js:/code/gulpfile.js
       - ./package.json:/code/package.json
       - ./tailwind.config.js:/code/tailwind.config.js
       - ./theme/assets/:/code/theme/assets/
       - ./theme/style.css:/code/theme/style.css
     command: ["run", "dev"]
volumes:
    db_data:
